### PR TITLE
feat: Adds minimal support for Devart Oracle client.

### PR DESCRIPTION
**Pull request by PhenX**
## Description

This adds support for auto instrumentation for the Devart Oracle driver

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)

### CODE REVIEW

**Comment by chynesNR** [comment]
Hi @PhenX, thanks so much for your submission! Typically when we add new instrumentation, we add integration tests for it. Would you be comfortable taking that on, or would you like us to do it? We'd be happy to, but it may take a few days for us to get to it.

**Comment by PhenX** [comment]
@chynesNR thank you for your quick answer, I'll give it a try, and take inspiration from the other SQL instrumentations. I'll tell you if it is too much for me.

**Comment by PhenX** [comment]
I can't find integration tests for Oracle, I think I won't be able to start from scratch, feel free to handle it :)

**Comment by chynesNR** [comment]
@PhenX - No worries! I should have time to get to it this week.

**Comment by PhenX** [comment]
Hello @chynesNR any news on this ? :)

**Review by nr-ahemsath — APPROVED** [review]
Low risk change.  Going to merge without integration tests and add a backlog item to add them at a later date.

**Review by tippmar-nr — APPROVED** [review]

**Pull request merged**
