### PR TITLE
Added New Unit Tests and Code Coverage Workflow

### PR DESCRIPTION
**Pull request by tippmar-nr**
## Description
Added Code Coverage collection during Unit Test execution and an accompanying GitHub workflow. Code coverage reports will be automatically uploaded to Codecov.io and are visible at https://app.codecov.io/github/newrelic/newrelic-dotnet-agent 

* Converted Unit Test `.csproj` files to "sdk" style.
* Added `coverlet.collector` and `Microsoft.Net.Test.SDK` packages to several Unit Test projects
* Added `run_unit_tests.yml` GitHub workflow to execute unit tests and upload results to codecov.io 
* Added `UnitTests.runsettings` to control how unit tests are executed (primarily to exclude the unit test projects from the code coverage collector).
* Added `codecov.yml` to configure CodeCov for the .NET Agent repo.

# Author Checklist
- [x] Unit tests, Integration tests, and Unbounded tests completed
- [x] Performance testing completed with satisfactory results (if required)
- [x] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

### CODE REVIEW

**Review by chynesNR — APPROVED** [review]
This all looks reasonable. Were you able to determine what the codecov token is used for?

**Comment by tippmar-nr** [comment]
> This all looks reasonable. Were you able to determine what the codecov token is used for?

The token ended up not being needed since we're using the CodeCov GitHub action to upload, the error I was seeing that prompted me to add the token must have been a transient of some kind. Works just fine without it.

**Review by JcolemanNR — APPROVED** [review]
Looks good to me! I think we may want to refactor the `run_unit_tests.yml` in to our existing `all_solutions.yml` at some point as we will now be running unit tests twice, but this works for now!

**Review by jaffinito — APPROVED** [review]
I like that we are starting out with a separate workflow.  It makes it a bit less risky since it won't block our PRs.

This looks awesome!

**Pull request merged**
