### PR TITLE
chore: Use Autofac instead of Castle.Windsor for .Net Framework builds

### PR DESCRIPTION
**Pull request by tippmar-nr**
Removes all references to `Castle.Windsor` and `Castle.Core`, removed `WindsorContainer`, renamed `CoreContainer` to `AgentContainer` and did some minor refactoring as needed.  #1782

### CODE REVIEW

**Review by jaffinito — APPROVED** [review]

**Comment by jaffinito** [comment]
Very cool!

**Comment by chynesNR** [comment]
Nice bit of cleanup! Looks like there are still a couple references to it in `OpenRastaWebApplication.csproj` and `BenchmarkingTests.csproj`. Can we get rid of those as well? Then we could remove the Castle.Windsor section from our [third party notices](https://github.com/newrelic/newrelic-dotnet-agent/blob/fb41c063caf10af0c4d64f4f7f63d097c674b822/licenses/THIRD_PARTY_NOTICES.txt#L99)

**Comment by tippmar-nr** [comment]
@chynesNR Looks like `OpenRastaWebApplication` still needs `Castle` for its DI configuration. Do we have to list packages used for integration tests in the Third Party Notices file?

**Review by nrcventura — APPROVED** [review]

**Review by chynesNR — APPROVED** [review]

**Comment by chynesNR** [comment]
> @chynesNR ~Looks like `OpenRastaWebApplication` still needs `Castle` for its DI configuration. Do we have to list packages used for integration tests in the Third Party Notices file?~
> 
> I was able to remove the DI references in `OpenRastaWebApplication` so `Castle` is no more...

Great!

**Pull request merged**
