### PR TITLE
NET35 - Update Integration Tests to support Protocol-15

### PR DESCRIPTION
**Pull request by jifeingo**
### Description

Modifies Integration Testing framework in support of Protocol-15
* MockNewRelic supports Preconnect and forces SSL
* Modifies test harneses and fixtures to closer align with 8.x branch.

### CODE REVIEW

**Comment by jifeingo** [comment]
jenkins retest this

**Comment by jifeingo** [comment]
jenkins retest this

**Comment by jifeingo** [comment]
jenkins retest this

**Comment by nr-ahemsath** [comment]
jenkins retest this

**Pull request closed without merging**
