### PR TITLE
Add style cop

### PR DESCRIPTION
**Pull request by lspangler584**
## Summary
Adds StyleCop to FullAgent, IntegrationsTests, and UnboundedIntegrationTests solutions in the main branch.

## Details

- Adds StyleCop.Analyzers NuGet package to `Common.src.props` and `Common.test.props`.
- Adds Common.ruleset to `build` dir.
     Rules marked "Error" will cause build failures when violated. 
- References ruleset from `build\Common.<xxx>.props
- Adds stylecop.json file to `build` dir to modify rules.
- Modifies existing file headers to adhere to default StyleCop schema.

This initial introduction will only include rules to validate the required copyright file headers are in place for all files.

## Links

- StyleCop [repo](https://github.com/StyleCop/StyleCop)
- StyleCop rule codes can be found [here](https://documentation.help/StyleCop/StyleCop%20Rules.html).

### CODE REVIEW

**Comment by lspangler584** [comment]
jenkins retest this

**Comment by jaffinito** [comment]
jenkins retest this

**Comment by jaffinito** [comment]
Looking over stylecop, its not going to work for the cpp projects: `StyleCop analyzes C# source code to enforce a set of style and consistency rules.`

You are likely going to have to add it on a per project basis.

**Comment by lspangler584** [comment]
Closing in favor of new branch/PR.

**Pull request closed without merging**
