### PR TITLE
Updates build icon to new logo

### PR DESCRIPTION
**Pull request by jaffinito**
## Description

- Updates build icon to new logo

I was going to update the .ico file as well, used in the installer, but it would not match the other logos used in the MSI. 

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)
- [ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

### CODE REVIEW

**Comment by chynesNR** [comment]
Do we know if there are any size restrictions on the icon? This one's much bigger.

**Comment by jaffinito** [comment]
Let double check something on the size.

**Comment by jaffinito** [comment]
Okay, the original file says it is 40x40, but it's not.  I resized it and I am pushing a change with the new one.
Nice catch!

**Comment by jaffinito** [comment]
New PNG has been pushed.  I double checked and it's only used in one place and there are no size parameters associated with it.

**Review by chynesNR — APPROVED** [review]
Looks good!

**Pull request merged**
