### PR TITLE
Cosmosdb client instrumentation support.

### PR DESCRIPTION
**Pull request by vuqtran88**
Adds CosmosDB client instrumentation support.

### CODE REVIEW

**Review by tehbio — APPROVED** [review]
Looks great! 🚢👋

**Review by jaffinito — APPROVED** [review]

**Comment by skurik** [comment]
Hi, could you please provide an example of how the CosmosDB data can be queried in NRQL?  I don't see any new attributes on `Transaction`, nor do I see any Cosmos-related spans in transactions that query Cosmos. Thanks!

**Comment by vuqtran88** [comment]
@skurik you should be able to see `CosmosDB` as value for the `component` attribute.

**Comment by skurik** [comment]
Thanks @vuqtran88, so it's the the `Span` data set. I don't see any Cosmos there, is some additional configuration required? I see `Redis` and `MSSQL` there.

**Comment by vuqtran88** [comment]
Hi @skurik I'm not exactly understood your question. There shouldn't be any additional configuration required. I'm curious about what query that you tried before that worked with `MSSQL` or `Redis` instrumentation, but didn't work with `CosmosDB` ? In other words, what attributes that you used for querying `MSSQL`/`Redis` calls ? This will help me better understand what you are looking for. Thanks.

**Comment by skurik** [comment]
@vuqtran88 The first place where I can see `MSSQL` / `Redis` call durations is the default APM dashboard:

image

I can also see MSSQL and Redis spans in transaction traces:

image

And I can of course query the span data:

image

So I was wondering why I wasn't seeing Cosmos operations recorded in these places as well.

**Comment by vuqtran88** [comment]
@skurik  would you mind sharing us:
1. What version of the agent you are using ?
2. What version of the `Microsoft.Azure.Cosmos` library you are using ?
3. Could give us an example of you CosmosDB call code snippet ?

**Comment by skurik** [comment]
@vuqtran88 Sure:

1. `NewRelic.Agent` 9.2.0 and `NewRelic.Agent.Api` 9.2.0
2. `Microsoft.Azure.Cosmos` 3.16.0
3. We're reading from Cosmos like this:

```csharp
    var query = container.GetItemLinqQueryable<T>(allowSynchronousQueryExecution: false)
                                     .Where(...);

    using (var cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(30)))
    {
         return GetQueryResult(query, cancellationTokenSource.Token);
    }    

    private List<T> GetQueryResult<T>(IQueryable<T> query, CancellationToken cancellationToken)
    {
        return GetActionResult(_ => Read(query, cancellationToken));
    }

    private async Task<IStrictEnumerable<T>> Read<T>(IQueryable<T> query, CancellationToken cancellationToken)
    {
        var resultCollection = new List<T>();
        using (var queryFeedIterator = query.ToFeedIterator())
        {
            while (queryFeedIterator.HasMoreResults)
            {
                var response = await queryFeedIterator.ReadNextAsync(cancellationToken);
                resultCollection.AddRange(response);
            }
        }

        return resultCollection;
    }
    
    private T GetActionResult<T>(Func<Unit, Task<T>> action)
    {
        using (var task = Task.Run(async () => await action(Unit.Value)))
        {
            return task.Result;
        }
    }
```

**Comment by vuqtran88** [comment]
> @vuqtran88 Sure:
> 
> 1. `NewRelic.Agent` 9.2.0 and `NewRelic.Agent.Api` 9.2.0
> 2. `Microsoft.Azure.Cosmos` 3.16.0
> 3. We're reading from Cosmos like this:
> 
> ```cs
>     var query = container.GetItemLinqQueryable<T>(allowSynchronousQueryExecution: false)
>                          .Where(...);
> 
>     using (var cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(30)))
>     {
>          return GetQueryResult(query, cancellationTokenSource.Token);
>     }    
> 
>     private List<T> GetQueryResult<T>(IQueryable<T> query, CancellationToken cancellationToken)
>     {
>         return GetActionResult(_ => Read(query, cancellationToken));
>     }
> 
>     private async Task<IStrictEnumerable<T>> Read<T>(IQueryable<T> query, CancellationToken cancellationToken)
>     {
>         var resultCollection = new List<T>();
>         using (var queryFeedIterator = query.ToFeedIterator())
>         {
>             while (queryFeedIterator.HasMoreResults)
>             {
>                 var response = await queryFeedIterator.ReadNextAsync(cancellationToken);
>                 resultCollection.AddRange(response);
>             }
>         }
> 
>         return resultCollection;
>     }
>     
>     private T GetActionResult<T>(Func<Unit, Task<T>> action)
>     {
>         using (var task = Task.Run(async () => await action(Unit.Value)))
>         {
>             return task.Result;
>         }
>     }
> ```

You need to use at least version 3.17 for the Cosmos client library. We called out here https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core/

**Comment by skurik** [comment]
That was indeed the problem 🤦‍♂️ Thanks a lot @vuqtran88!

**Pull request merged**
