### PR TITLE
Update SQSRequestHandler.cs - Fix 2811

### PR DESCRIPTION
**Pull request by indy-singh**
This quick fixes dynamically pulling out a property see https://github.com/newrelic/newrelic-dotnet-agent/issues/2811

### CODE REVIEW

**Comment by nr-ahemsath** [comment]
Thank you for submitting a PR.  At first glance, your changes make sense.  However, on our end we need to do some more research to understand how this scenario can occur, and come up with a reliable reproduction case.  Thank your for your patience while we do the analysis.

**Comment by indy-singh** [comment]
Hi @nr-ahemsath,

It will be an empty `ReceiveMessageResponse`, so the scenario is the queue was polled but it had no messages to action. So an empty response T was received. Depending on how the consumer has configured their AWS SDK; the collection on T is either empty or null.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_ResponseElements

https://github.com/aws/aws-sdk-net/blob/b5c10d5d48299f6c68286ee48039bc4ecbc21019/sdk/src/Services/SQS/Generated/Model/ReceiveMessageResponse.cs#L37

Happy to close the PR, if you guys want to deep dive on it.

Cheers,
Indy

**Comment by nr-ahemsath** [comment]
@indy-singh Thanks for the additional info, that will be very helpful.  We're happy to leave the PR open for now.

**Comment by nr-ahemsath** [comment]
@indy-singh Thanks again for the initial take on this fix.  This PR has a more complete version of the fix, plus testing: https://github.com/newrelic/newrelic-dotnet-agent/pull/2833/

Will close this one now.

**Pull request closed without merging**
