### PR TITLE
Add Dotty slack bot.

### PR DESCRIPTION
**Pull request by jackdelamotte**
## Description

Adds the Dotty Slack bot to notify team of updates to our core technologies.

# Author Checklist
- [ ] Unit tests, Integration tests, and Unbounded tests completed
- [ ] Performance testing completed with satisfactory results (if required)
- [ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [x] Perform code review
- [x] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

### CODE REVIEW

**Comment by jackdelamotte** [comment]
Noting that by adding a skeleton workflow in a separate PR (#1241), it is now possible to run the workflow from the Actions tab and is currently [running successfully](https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/3018805693)

**Review by nr-ahemsath — APPROVED** [review]
Looks good.  Thanks for including the link to the successful run in the PR description.  🚢

**Comment by chynesNR** [comment]
Looks pretty good! It doesn't have to be anything fancy, but maybe it could use a little error handling? If something went wrong, for example, parsing the JSON for one of the packages, it would just crash and we wouldn't know, since no output means no new packages.

**Comment by nr-ahemsath** [comment]
> Looks pretty good! It doesn't have to be anything fancy, but maybe it could use a little error handling? If something went wrong, for example, parsing the JSON for one of the packages, it would just crash and we wouldn't know, since no output means no new packages.

Another good reason to instrument it with our agent. 😄

**Pull request merged**
