### PR TITLE
Log instrumentation

### PR DESCRIPTION
**Pull request by JcolemanNR**
## Description

This adds the ability to automatically instrument/forward/decorate log messages in the .NET agent for Log4net, Microsoft Extension Logging, and Serilog.

# Author Checklist
- [x] Unit tests, Integration tests, and Unbounded tests completed
- [x] Performance testing completed with satisfactory results (if required)
- [x] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Pull request was adequately tested (new/existing tests, performance tests)
- [ ] Review Changelog

### CODE REVIEW

**Review by jaffinito — APPROVED** [review]
Review done via pairing with Josh.
Approved!

**Comment by Lonli-Lokli** [comment]
Is there any documentation on how this can enabled?

**Comment by angelatan2** [comment]
Hello @Lonli-Lokli, here is a link to the [documentation](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#automatic). Please note that we are in the process of updating some of the guidance based on feedback from @amweiss. You can find those changes in process here: https://github.com/newrelic/newrelic-dotnet-agent/issues/1050#issuecomment-1095029390.  These updates to the documentation will be released shortly.

**Comment by Lonli-Lokli** [comment]
@angelatan2 thanks for the link!

Will these options be customizable via environment variables? That's an easiest way for docker-based solutions

**Comment by nr-ahemsath** [comment]
@Lonli-Lokli Thanks for pointing out the gap in our documentation, I'll be updating it to include the environment variable options.

**Pull request merged**
