### PR TITLE
Fit/eu support

### PR DESCRIPTION
**Pull request by hsinghkalsi**
### Description
Support Protocol v15 for .NET Agent 6.5 branch.

### Testing
Manual testing.  Added cross agent test suite from 8.x branch.

### CODE REVIEW

**Comment by nr-ahemsath** [comment]
ci test this please

**Comment by hsinghkalsi** [comment]
@jifeingo added preconnect support

**Comment by jifeingo** [comment]
CI test this

**Comment by jifeingo** [comment]
jenkins retest this

**Comment by jifeingo** [comment]
jenkins retest this

**Comment by lspangler584** [comment]
ci test this

**Comment by lspangler584** [comment]
jenkins retest this

**Review by jifeingo — APPROVED** [review]

**Pull request merged**
